GET http://localhost:5000/users

###
GET http://localhost:5000/users/


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Wisnu",
    "email":"abc@gmail.com",
    "password":"qbc123",
    "confPassword":"qbc123",
    "role":"admin"
}
