GET http://localhost:5000/users

###
GET http://localhost:5000/users/ba91b276-bb3b-41ed-9080-62a1df8e452b


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Wisnu",
    "email":"abc@gmail.com",
    "password":"qbc123",
    "role":"admin"
}
